export const NUMBER_OF_ORDER_BOOK = 16;

export const TOTAL_DECIMAL: { [key: string]: number } = {
  BTC_USDT: 8,
  LTC_USDT: 7,
  LTC_BTC: 8,
  ETH_USDT: 7,
  ETH_BTC: 6,
  XRP_USDT: 6,
  XRP_USD: 6,
  XRP_BTC: 8,
  BCH_USDT: 2,
  BCH_USD: 2,
  BCH_BTC: 4,
  XTZ_USDT: 2,
  XTZ_USD: 2,
  XTZ_BTC: 7,
  LINK_USDT: 2,
  LINK_USD: 2,
  LINK_BTC: 6,
  XLM_USDT: 3,
  XLM_USD: 3,
  XLM_BTC: 7,
  ADA_USDT: 2,
  ADA_BTC: 7,
  OMG_USDT: 2,
  OMG_BTC: 6,
  MKR_USDT: 3,
  MKR_USD: 3,
  MKR_BTC: 4,
  UNI_USDT: 2,
  UNI_BTC: 6,
  BNB_USDT: 3,
  BNB_USD: 3,
  BNB_BTC: 5,
  SOL_USDT: 3,
  SOL_BTC: 6,
  MATIC_USDT: 2,
  MATIC_USD: 2,
  MATIC_BTC: 7,
  AVAX_BTC: 6,
  AVAX_USDT: 2,
  SAND_BTC: 7,
  SAND_USDT: 3,
  SAND_USD: 3,
  MANA_BTC: 7,
  MANA_USDT: 3,
  MANA_USD: 3,
  BTC_USD: 8,
  ETH_USD: 7,
  LTC_USD: 7,
  ORBS_USDT: 6,
  ORBS_USD: 6,
  ATOM_BTC: 6,
  ATOM_USDT: 2,
  ATOM_USD: 2,
  SOL_USD: 3,
  OMG_USD: 2,
  AVAX_USD: 2,
  DOGE_BTC: 7,
  DOGE_USDT: 3,
  DOGE_USD: 3,
  SHIB_USDT: 7,
  SHIB_USD: 7,
  FTM_USDT: 3,
  FTM_USD: 3,
  FTM_BTC: 7,
  DOT_BTC: 6,
  DOT_USDT: 1,
  DOT_USD: 1,
  IOTX_USDT: 4,
  IOTX_USD: 4,
  LUNA_USDT: 3,
  LUNA_USD: 3,
  LUNC_USDT: 7,
  LUNC_USD: 7,
  YGG_USDT: 3,
  KP3R_USDT: 3,
  ETHW_USDT: 7,
  ETHW_BTC: 6,
  ETHS_USDT: 7,
  ETHS_BTC: 6,
};

export const COIN_DECIMAL: { [key: string]: number } = {
  BTC: 8,
  USDT: 2,
};

export const FIX_CROSS_LINE = true;
