export const countries: Record<string, { name: string; dial_code: string; currency: string; nationality: string }> = {
  AF: {
    name: 'Afghanistan',
    dial_code: '+93',
    currency: 'AFN',
    nationality: 'Afghan',
  },
  AL: {
    name: 'Albania',
    dial_code: '+355',
    currency: 'ALL',
    nationality: 'Albanian',
  },
  DZ: {
    name: 'Algeria',
    dial_code: '+213',
    currency: 'DZD',
    nationality: 'Algerian',
  },
  AS: {
    name: 'American Samoa',
    dial_code: '+1 684',
    currency: 'EUR',
    nationality: 'American Samoan',
  },
  AD: {
    name: 'Andorra',
    dial_code: '+376',
    currency: 'EUR',
    nationality: 'Andorran',
  },
  AO: {
    name: 'Angola',
    dial_code: '+244',
    currency: 'AOA',
    nationality: 'Angolan',
  },
  AI: {
    name: 'Anguilla',
    dial_code: '+1 264',
    currency: 'XCD',
    nationality: 'Anguillan',
  },
  AG: {
    name: 'Antigua and Barbuda',
    dial_code: '+1 268',
    currency: 'XCD',
    nationality: 'Antiguan or Barbudan',
  },
  AR: {
    name: 'Argentina',
    dial_code: '+54',
    currency: 'ARS',
    nationality: 'Argentine',
  },
  AM: {
    name: 'Armenia',
    dial_code: '+374',
    currency: 'AMD',
    nationality: 'Armenian',
  },
  AW: {
    name: 'Aruba',
    dial_code: '+297',
    currency: 'ANG',
    nationality: 'Aruban',
  },
  AU: {
    name: 'Australia',
    dial_code: '+61',
    currency: 'AUD',
    nationality: 'Australian',
  },
  AT: {
    name: 'Austria',
    dial_code: '+43',
    currency: 'EUR',
    nationality: 'Austrian',
  },
  AZ: {
    name: 'Azerbaijan',
    dial_code: '+994',
    currency: 'AZN',
    nationality: 'Azerbaijani, Azeri',
  },
  BS: {
    name: 'Bahamas',
    dial_code: '+1 242',
    currency: 'BSD',
    nationality: 'Bahamian',
  },
  BH: {
    name: 'Bahrain',
    dial_code: '+973',
    currency: 'BHD',
    nationality: 'Bahraini',
  },
  BD: {
    name: 'Bangladesh',
    dial_code: '+880',
    currency: 'BDT',
    nationality: 'Bangladeshi',
  },
  BB: {
    name: 'Barbados',
    dial_code: '+1 246',
    currency: 'BBD',
    nationality: 'Barbadian',
  },
  BY: {
    name: 'Belarus',
    dial_code: '+375',
    currency: 'BYR',
    nationality: 'Belarusian',
  },
  BE: {
    name: 'Belgium',
    dial_code: '+32',
    currency: 'EUR',
    nationality: 'Belgian',
  },
  BZ: {
    name: 'Belize',
    dial_code: '+501',
    currency: 'BZD',
    nationality: 'Belizean',
  },
  BJ: {
    name: 'Benin',
    dial_code: '+229',
    currency: 'XOF',
    nationality: 'Beninese, Beninois',
  },
  BM: {
    name: 'Bermuda',
    dial_code: '+1 441',
    currency: 'BMD',
    nationality: 'Bermudian, Bermudan',
  },
  BT: {
    name: 'Bhutan',
    dial_code: '+975',
    currency: 'INR',
    nationality: 'Bhutanese',
  },
  BO: {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    currency: 'BOB',
    nationality: 'Bolivian',
  },
  BA: {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    currency: 'BAM',
    nationality: 'Bosnian or Herzegovinian',
  },
  BW: {
    name: 'Botswana',
    dial_code: '+267',
    currency: 'BWP',
    nationality: 'Motswana, Botswanan',
  },
  BR: {
    name: 'Brazil',
    dial_code: '+55',
    currency: 'BRL',
    nationality: 'Brazilian',
  },
  IO: {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    currency: 'USD',
    nationality: 'BIOT',
  },
  BG: {
    name: 'Bulgaria',
    dial_code: '+359',
    currency: 'BGN',
    nationality: 'Bulgarian',
  },
  BF: {
    name: 'Burkina Faso',
    dial_code: '+226',
    currency: 'XOF',
    nationality: 'Burkinabé',
  },
  BI: {
    name: 'Burundi',
    dial_code: '+257',
    currency: 'BIF',
    nationality: 'Burundian',
  },
  KH: {
    name: 'Cambodia',
    dial_code: '+855',
    currency: 'KHR',
    nationality: 'Cambodian',
  },
  CM: {
    name: 'Cameroon',
    dial_code: '+237',
    currency: 'XAF',
    nationality: 'Cameroonian',
  },
  CA: {
    name: 'Canada',
    dial_code: '+1',
    currency: 'CAD',
    nationality: 'Canadian',
  },
  CV: {
    name: 'Cape Verde',
    dial_code: '+238',
    currency: 'CVE',
    nationality: 'Cabo Verdean',
  },
  KY: {
    name: 'Cayman Islands',
    dial_code: '+345',
    currency: 'KYD',
    nationality: 'Caymanian',
  },
  CF: {
    name: 'Central African Republic',
    dial_code: '+236',
    currency: 'XAF',
    nationality: 'Central African',
  },
  TD: {
    name: 'Chad',
    dial_code: '+235',
    currency: 'XAF',
    nationality: 'Chadian',
  },
  CL: {
    name: 'Chile',
    dial_code: '+56',
    currency: 'CLP',
    nationality: 'Chilean',
  },
  CN: {
    name: 'China',
    dial_code: '+86',
    currency: 'CNY',
    nationality: 'Chinese',
  },
  CO: {
    name: 'Colombia',
    dial_code: '+57',
    currency: 'COP',
    nationality: 'Colombian',
  },
  KM: {
    name: 'Comoros',
    dial_code: '+269',
    currency: 'KMF',
    nationality: 'Comoran, Comorian',
  },
  CG: {
    name: 'Congo',
    dial_code: '+242',
    currency: 'XAF',
    nationality: 'Congolese',
  },
  CD: {
    name: 'Democratic Republic of the Congo',
    dial_code: '+243',
    currency: 'CDF',
    nationality: 'Democratic Republic of the Congo',
  },
  CK: {
    name: 'Cook Islands',
    dial_code: '+682',
    currency: 'NZD',
    nationality: 'Cook Island',
  },
  CR: {
    name: 'Costa Rica',
    dial_code: '+506',
    currency: 'CRC',
    nationality: 'Costa Rican',
  },
  CI: {
    name: "Côte d'Ivoire",
    dial_code: '+225',
    currency: 'XOF',
    nationality: 'Ivorian',
  },
  HR: {
    name: 'Croatia',
    dial_code: '+385',
    currency: 'HRK',
    nationality: 'Croatian',
  },
  CU: {
    name: 'Cuba',
    dial_code: '+53',
    currency: 'CUP',
    nationality: 'Cuban',
  },
  CW: {
    name: 'Curaçao',
    dial_code: '+599',
    currency: 'ANG',
    nationality: 'Curaçaoan',
  },
  CY: {
    name: 'Cyprus',
    dial_code: '+537',
    currency: 'CYP',
    nationality: 'Cypriot',
  },
  CZ: {
    name: 'Czech Republic',
    dial_code: '+420',
    currency: 'CZK',
    nationality: 'Czech',
  },
  DK: {
    name: 'Denmark',
    dial_code: '+45',
    currency: 'DKK',
    nationality: 'Danish',
  },
  DJ: {
    name: 'Djibouti',
    dial_code: '+253',
    currency: 'DJF',
    nationality: 'Djiboutian',
  },
  DM: {
    name: 'Dominica',
    dial_code: '+1 767',
    currency: 'XCD',
    nationality: 'Dominican',
  },
  DO: {
    name: 'Dominican Republic',
    dial_code: '+1 849',
    currency: 'DOP',
    nationality: 'Dominican Republic',
  },
  EC: {
    name: 'Ecuador',
    dial_code: '+593',
    currency: 'ECS',
    nationality: 'Ecuadorian',
  },
  EG: {
    name: 'Egypt',
    dial_code: '+20',
    currency: 'EGP',
    nationality: 'Egyptian',
  },
  SV: {
    name: 'El Salvador',
    dial_code: '+503',
    currency: 'SVC',
    nationality: 'Salvadoran',
  },
  GQ: {
    name: 'Equatorial Guinea',
    dial_code: '+240',
    currency: 'XAF',
    nationality: 'Equatorial Guinean, Equatoguinean',
  },
  ER: {
    name: 'Eritrea',
    dial_code: '+291',
    currency: 'ETB',
    nationality: 'Eritrean',
  },
  EE: {
    name: 'Estonia',
    dial_code: '+372',
    currency: 'EEK',
    nationality: 'Estonian',
  },
  ET: {
    name: 'Ethiopia',
    dial_code: '+251',
    currency: 'ETB',
    nationality: 'Ethiopian',
  },
  FK: {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    currency: 'FKP',
    nationality: 'Falkland Island',
  },
  FO: {
    name: 'Faroe Islands',
    dial_code: '+298',
    currency: 'DKK',
    nationality: 'Faroese',
  },
  FJ: {
    name: 'Fiji',
    dial_code: '+679',
    currency: 'FJD',
    nationality: 'Fijian',
  },
  FI: {
    name: 'Finland',
    dial_code: '+358',
    currency: 'EUR',
    nationality: 'Finnish',
  },
  FR: {
    name: 'France',
    dial_code: '+33',
    currency: 'EUR',
    nationality: 'French',
  },
  PF: {
    name: 'French Polynesia',
    dial_code: '+689',
    currency: 'XPF',
    nationality: 'French Polynesian',
  },
  GA: {
    name: 'Gabon',
    dial_code: '+241',
    currency: 'XAF',
    nationality: 'Gabonese',
  },
  GM: {
    name: 'Gambia',
    dial_code: '+220',
    currency: 'GMD',
    nationality: 'Gambian',
  },
  GE: {
    name: 'Georgia',
    dial_code: '+995',
    currency: 'GEL',
    nationality: 'Georgian',
  },
  DE: {
    name: 'Germany',
    dial_code: '+49',
    currency: 'EUR',
    nationality: 'German',
  },
  GH: {
    name: 'Ghana',
    dial_code: '+233',
    currency: 'GHS',
    nationality: 'Ghanaian',
  },
  GI: {
    name: 'Gibraltar',
    dial_code: '+350',
    currency: 'GIP',
    nationality: 'Gibraltar',
  },
  GR: {
    name: 'Greece',
    dial_code: '+30',
    currency: 'EUR',
    nationality: 'Greek, Hellenic',
  },
  GL: {
    name: 'Greenland',
    dial_code: '+299',
    currency: 'DKK',
    nationality: 'Greenlandic',
  },
  GD: {
    name: 'Grenada',
    dial_code: '+1 473',
    currency: 'XCD',
    nationality: 'Grenadian',
  },
  GU: {
    name: 'Guam',
    dial_code: '+1 671',
    currency: 'USD',
    nationality: 'Guamanian, Guambat',
  },
  GT: {
    name: 'Guatemala',
    dial_code: '+502',
    currency: 'GTQ',
    nationality: 'Guatemalan',
  },
  GG: {
    name: 'Guernsey',
    dial_code: '+44',
    currency: 'GGP',
    nationality: 'Channel Island',
  },
  GN: {
    name: 'Guinea',
    dial_code: '+224',
    currency: 'GNF',
    nationality: 'Guinean',
  },
  GW: {
    name: 'Guinea-Bissau',
    dial_code: '+245',
    currency: 'XOF',
    nationality: 'Bissau-Guinean',
  },
  HT: {
    name: 'Haiti',
    dial_code: '+509',
    currency: 'HTG',
    nationality: 'Haitian',
  },
  HN: {
    name: 'Honduras',
    dial_code: '+504',
    currency: 'HNL',
    nationality: 'Honduran',
  },
  HK: {
    name: 'Hong Kong',
    dial_code: '+852',
    currency: 'HKD',
    nationality: 'Hong Kong, Hong Kongese',
  },
  HU: {
    name: 'Hungary',
    dial_code: '+36',
    currency: 'HUF',
    nationality: 'Hungarian, Magyar',
  },
  IS: {
    name: 'Iceland',
    dial_code: '+354',
    currency: 'ISK',
    nationality: 'Icelandic',
  },
  IN: {
    name: 'India',
    dial_code: '+91',
    currency: 'INR',
    nationality: 'Indian',
  },
  ID: {
    name: 'Indonesia',
    dial_code: '+62',
    currency: 'IDR',
    nationality: 'Indonesian',
  },
  IR: {
    name: 'Iran, Islamic Republic of',
    dial_code: '+98',
    currency: 'IRR',
    nationality: 'Iranian, Persian',
  },
  IQ: {
    name: 'Iraq',
    dial_code: '+964',
    currency: 'IQD',
    nationality: 'Iraqi',
  },
  IE: {
    name: 'Ireland',
    dial_code: '+353',
    currency: 'EUR',
    nationality: 'Irish',
  },
  IM: {
    name: 'Isle of Man',
    dial_code: '+44',
    currency: 'GBP',
    nationality: 'Manx',
  },
  IL: {
    name: 'Israel',
    dial_code: '+972',
    currency: 'ILS',
    nationality: 'Israeli',
  },
  IT: {
    name: 'Italy',
    dial_code: '+39',
    currency: 'EUR',
    nationality: 'Italian',
  },
  JM: {
    name: 'Jamaica',
    dial_code: '+1 876',
    currency: 'JMD',
    nationality: 'Jamaican',
  },
  JP: {
    name: 'Japan',
    dial_code: '+81',
    currency: 'JPY',
    nationality: 'Japanese',
  },
  JE: {
    name: 'Jersey',
    dial_code: '+44',
    currency: 'GBP',
    nationality: 'Channel Island',
  },
  JO: {
    name: 'Jordan',
    dial_code: '+962',
    currency: 'JOD',
    nationality: 'Jordanian',
  },
  KZ: {
    name: 'Kazakhstan',
    dial_code: '+7 7',
    currency: 'KZT',
    nationality: 'Kazakhstani, Kazakh',
  },
  KE: {
    name: 'Kenya',
    dial_code: '+254',
    currency: 'KES',
    nationality: 'Kenyan',
  },
  KI: {
    name: 'Kiribati',
    dial_code: '+686',
    currency: 'AUD',
    nationality: 'I-Kiribati',
  },
  KP: {
    name: 'North Korea',
    dial_code: '+850',
    currency: 'KPW',
    nationality: 'North Korean',
  },
  KR: {
    name: 'South Korea',
    dial_code: '+82',
    currency: 'KRW',
    nationality: 'South Korean',
  },
  KW: {
    name: 'Kuwait',
    dial_code: '+965',
    currency: 'KWD',
    nationality: 'Kuwaiti',
  },
  KG: {
    name: 'Kyrgyzstan',
    dial_code: '+996',
    currency: 'KGS',
    nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz',
  },
  LA: {
    name: "Lao People's Democratic Republic",
    dial_code: '+856',
    currency: 'LAK',
    nationality: 'Lao, Laotian',
  },
  LV: {
    name: 'Latvia',
    dial_code: '+371',
    currency: 'LVL',
    nationality: 'Latvian',
  },
  LB: {
    name: 'Lebanon',
    dial_code: '+961',
    currency: 'LBP',
    nationality: 'Lebanese',
  },
  LS: {
    name: 'Lesotho',
    dial_code: '+266',
    currency: 'LSL',
    nationality: 'Basotho',
  },
  LR: {
    name: 'Liberia',
    dial_code: '+231',
    currency: 'LRD',
    nationality: 'Liberian',
  },
  LY: {
    name: 'Libya',
    dial_code: '+218',
    currency: 'LYD',
    nationality: 'Libyan',
  },
  LI: {
    name: 'Liechtenstein',
    dial_code: '+423',
    currency: 'CHF',
    nationality: 'Liechtenstein',
  },
  LT: {
    name: 'Lithuania',
    dial_code: '+370',
    currency: 'LTL',
    nationality: 'Lithuanian',
  },
  LU: {
    name: 'Luxembourg',
    dial_code: '+352',
    currency: 'EUR',
    nationality: 'Luxembourg, Luxembourgish',
  },
  MO: {
    name: 'Macao',
    dial_code: '+853',
    currency: 'MOP',
    nationality: 'Macanese, Chinese',
  },
  MK: {
    name: 'Republic of Macedonia',
    dial_code: '+389',
    currency: 'MKD',
    nationality: 'Macedonian',
  },
  MG: {
    name: 'Madagascar',
    dial_code: '+261',
    currency: 'MGA',
    nationality: 'Malagasy',
  },
  MW: {
    name: 'Malawi',
    dial_code: '+265',
    currency: 'MWK',
    nationality: 'Malawian',
  },
  MY: {
    name: 'Malaysia',
    dial_code: '+60',
    currency: 'MYR',
    nationality: 'Malaysian',
  },
  MV: {
    name: 'Maldives',
    dial_code: '+960',
    currency: 'MVR',
    nationality: 'Maldivian',
  },
  ML: {
    name: 'Mali',
    dial_code: '+223',
    currency: 'XOF',
    nationality: 'Malian, Malinese',
  },
  MT: {
    name: 'Malta',
    dial_code: '+356',
    currency: 'MTL',
    nationality: 'Maltese',
  },
  MH: {
    name: 'Marshall Islands',
    dial_code: '+692',
    currency: 'USD',
    nationality: 'Marshallese',
  },
  MQ: {
    name: 'Martinique',
    dial_code: '+596',
    currency: 'EUR',
    nationality: 'Martiniquais, Martinican',
  },
  MR: {
    name: 'Mauritania',
    dial_code: '+222',
    currency: 'MRO',
    nationality: 'Mauritanian',
  },
  MU: {
    name: 'Mauritius',
    dial_code: '+230',
    currency: 'MUR',
    nationality: 'Mauritian',
  },
  MX: {
    name: 'Mexico',
    dial_code: '+52',
    currency: 'MXN',
    nationality: 'Mexican',
  },
  FM: {
    name: 'Micronesia, Federated States of',
    dial_code: '+691',
    currency: 'USD',
    nationality: 'Micronesian',
  },
  MD: {
    name: 'Republic of Moldova',
    dial_code: '+373',
    currency: 'MDL',
    nationality: 'Moldovan',
  },
  MC: {
    name: 'Monaco',
    dial_code: '+377',
    currency: 'EUR',
    nationality: 'Monégasque, Monacan',
  },
  MN: {
    name: 'Mongolia',
    dial_code: '+976',
    currency: 'MNT',
    nationality: 'Mongolian',
  },
  ME: {
    name: 'Montenegro',
    dial_code: '+382',
    currency: 'EUR',
    nationality: 'Montenegrin',
  },
  MS: {
    name: 'Montserrat',
    dial_code: '+1664',
    currency: 'XCD',
    nationality: 'Montserratian',
  },
  MA: {
    name: 'Morocco',
    dial_code: '+212',
    currency: 'MAD',
    nationality: 'Moroccan',
  },
  MZ: {
    name: 'Mozambique',
    dial_code: '+258',
    currency: 'MZN',
    nationality: 'Mozambican',
  },
  MM: {
    name: 'Myanmar',
    dial_code: '+95',
    currency: 'MMK',
    nationality: 'Burmese',
  },
  NA: {
    name: 'Namibia',
    dial_code: '+264',
    currency: 'NAD',
    nationality: 'Namibian',
  },
  NR: {
    name: 'Nauru',
    dial_code: '+674',
    currency: 'AUD',
    nationality: 'Nauruan',
  },
  NP: {
    name: 'Nepal',
    dial_code: '+977',
    currency: 'NPR',
    nationality: 'Nepali, Nepalese',
  },
  NL: {
    name: 'Netherlands',
    dial_code: '+31',
    currency: 'EUR',
    nationality: 'Dutch, Netherlandic',
  },
  NZ: {
    name: 'New Zealand',
    dial_code: '+64',
    currency: 'NZD',
    nationality: 'New Zealand, NZ',
  },
  NI: {
    name: 'Nicaragua',
    dial_code: '+505',
    currency: 'NIO',
    nationality: 'Nicaraguan',
  },
  NE: {
    name: 'Niger',
    dial_code: '+227',
    currency: 'XOF',
    nationality: 'Nigerien',
  },
  NG: {
    name: 'Nigeria',
    dial_code: '+234',
    currency: 'NGN',
    nationality: 'Nigerian',
  },
  NU: {
    name: 'Niue',
    dial_code: '+683',
    currency: 'NZD',
    nationality: 'Niuean',
  },
  NF: {
    name: 'Norfolk Island',
    dial_code: '+672',
    currency: 'AUD',
    nationality: 'Norfolk Island',
  },
  MP: {
    name: 'Northern Mariana Islands',
    dial_code: '+1 670',
    currency: 'USD',
    nationality: 'Northern Marianan',
  },
  NO: {
    name: 'Norway',
    dial_code: '+47',
    currency: 'NOK',
    nationality: 'Norwegian',
  },
  OM: {
    name: 'Oman',
    dial_code: '+968',
    currency: 'OMR',
    nationality: 'Omani',
  },
  PK: {
    name: 'Pakistan',
    dial_code: '+92',
    currency: 'PKR',
    nationality: 'Pakistani',
  },
  PW: {
    name: 'Palau',
    dial_code: '+680',
    currency: 'USD',
    nationality: 'Palauan',
  },
  PS: {
    name: 'Palestinian Territory',
    dial_code: '+970',
    currency: 'JOD',
    nationality: 'Palestinian',
  },
  PA: {
    name: 'Panama',
    dial_code: '+507',
    currency: 'PAB',
    nationality: 'Panamanian',
  },
  PG: {
    name: 'Papua New Guinea',
    dial_code: '+675',
    currency: 'PGK',
    nationality: 'Papua New Guinean, Papuan',
  },
  PY: {
    name: 'Paraguay',
    dial_code: '+595',
    currency: 'PYG',
    nationality: 'Paraguayan',
  },
  PE: {
    name: 'Peru',
    dial_code: '+51',
    currency: 'PEN',
    nationality: 'Peruvian',
  },
  PH: {
    name: 'Philippines',
    dial_code: '+63',
    currency: 'PHP',
    nationality: 'Philippine, Filipino',
  },
  PN: {
    name: 'Pitcairn',
    dial_code: '+872',
    currency: 'NZD',
    nationality: 'Pitcairn Island',
  },
  PL: {
    name: 'Poland',
    dial_code: '+48',
    currency: 'PLN',
    nationality: 'Polish',
  },
  PT: {
    name: 'Portugal',
    dial_code: '+351',
    currency: 'EUR',
    nationality: 'Portuguese',
  },
  PR: {
    name: 'Puerto Rico',
    dial_code: '+1 939',
    currency: 'USD',
    nationality: 'Puerto Rican',
  },
  QA: {
    name: 'Qatar',
    dial_code: '+974',
    currency: 'QAR',
    nationality: 'Qatari',
  },
  RO: {
    name: 'Romania',
    dial_code: '+40',
    currency: 'RON',
    nationality: 'Romanian',
  },
  RU: {
    name: 'Russian',
    dial_code: '+7',
    currency: 'RUB',
    nationality: 'Russian',
  },
  RW: {
    name: 'Rwanda',
    dial_code: '+250',
    currency: 'RWF',
    nationality: 'Rwandan',
  },
  KN: {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1 869',
    currency: 'XCD',
    nationality: 'Kittitian or Nevisian',
  },
  WS: {
    name: 'Samoa',
    dial_code: '+685',
    currency: 'EUR',
    nationality: 'Samoan',
  },
  SM: {
    name: 'San Marino',
    dial_code: '+378',
    currency: 'EUR',
    nationality: 'Sammarinese',
  },
  ST: {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    currency: 'STD',
    nationality: 'São Toméan',
  },
  SA: {
    name: 'Saudi Arabia',
    dial_code: '+966',
    currency: 'SAR',
    nationality: 'Saudi, Saudi Arabian',
  },
  SN: {
    name: 'Senegal',
    dial_code: '+221',
    currency: 'XOF',
    nationality: 'Senegalese',
  },
  RS: {
    name: 'Serbia',
    dial_code: '+381',
    currency: 'RSD',
    nationality: 'Serbian',
  },
  SC: {
    name: 'Seychelles',
    dial_code: '+248',
    currency: 'SCR',
    nationality: 'Seychellois',
  },
  SL: {
    name: 'Sierra Leone',
    dial_code: '+232',
    currency: 'SLL',
    nationality: 'Sierra Leonean',
  },
  SG: {
    name: 'Singapore',
    dial_code: '+65',
    currency: 'SGD',
    nationality: 'Singaporean',
  },
  SX: {
    name: 'Sint Maarten',
    dial_code: '+599',
    currency: 'ANG',
    nationality: 'Sint Maarten',
  },
  SK: {
    name: 'Slovakia',
    dial_code: '+421',
    currency: 'SKK',
    nationality: 'Slovak',
  },
  SI: {
    name: 'Slovenia',
    dial_code: '+386',
    currency: 'EUR',
    nationality: 'Slovenian, Slovene',
  },
  SB: {
    name: 'Solomon Islands',
    dial_code: '+677',
    currency: 'SBD',
    nationality: 'Solomon Island',
  },
  SO: {
    name: 'Somalia',
    dial_code: '+252',
    currency: 'SOS',
    nationality: 'Somali, Somalian',
  },
  ZA: {
    name: 'South Africa',
    dial_code: '+27',
    currency: 'ZAR',
    nationality: 'South African',
  },
  SS: {
    name: 'South Sudan',
    dial_code: '+211',
    currency: 'SSP',
    nationality: 'South Sudanese',
  },
  ES: {
    name: 'Spain',
    dial_code: '+34',
    currency: 'EUR',
    nationality: 'Spanish',
  },
  LK: {
    name: 'Sri Lanka',
    dial_code: '+94',
    currency: 'LKR',
    nationality: 'Sri Lankan',
  },
  SD: {
    name: 'Sudan',
    dial_code: '+249',
    currency: 'SDG',
    nationality: 'Sudanese',
  },
  SR: {
    name: 'Suriname',
    dial_code: '+597',
    currency: 'SRD',
    nationality: 'Surinamese',
  },
  SZ: {
    name: 'Swaziland',
    dial_code: '+268',
    currency: 'SZL',
    nationality: 'Swazi',
  },
  SE: {
    name: 'Sweden',
    dial_code: '+46',
    currency: 'SEK',
    nationality: 'Swedish',
  },
  CH: {
    name: 'Switzerland',
    dial_code: '+41',
    currency: 'CHF',
    nationality: 'Swiss',
  },
  SY: {
    name: 'Syria',
    dial_code: '+963',
    currency: 'SYP',
    nationality: 'Syrian',
  },
  TW: {
    name: 'Taiwan, Province of China',
    dial_code: '+886',
    currency: 'TWD',
    nationality: 'Chinese, Taiwanese',
  },
  TJ: {
    name: 'Tajikistan',
    dial_code: '+992',
    currency: 'TJS',
    nationality: 'Tajikistani',
  },
  TZ: {
    name: 'Tanzania',
    dial_code: '+255',
    currency: 'TZS',
    nationality: 'Tanzanian',
  },
  TH: {
    name: 'Thailand',
    dial_code: '+66',
    currency: 'THB',
    nationality: 'Thai',
  },
  TG: {
    name: 'Togo',
    dial_code: '+228',
    currency: 'XOF',
    nationality: 'Togolese',
  },
  TK: {
    name: 'Tokelau',
    dial_code: '+690',
    currency: 'NZD',
    nationality: 'Tokelauan',
  },
  TO: {
    name: 'Tonga',
    dial_code: '+676',
    currency: 'TOP',
    nationality: 'Tongan',
  },
  TT: {
    name: 'Trinidad and Tobago',
    dial_code: '+1 868',
    currency: 'TTD',
    nationality: 'Trinidadian or Tobagonian',
  },
  TN: {
    name: 'Tunisia',
    dial_code: '+216',
    currency: 'TND',
    nationality: 'Tunisian',
  },
  TR: {
    name: 'Turkey',
    dial_code: '+90',
    currency: 'TRY',
    nationality: 'Turkish',
  },
  TM: {
    name: 'Turkmenistan',
    dial_code: '+993',
    currency: 'TMT',
    nationality: 'Turkmen',
  },
  TC: {
    name: 'Turks and Caicos Islands',
    dial_code: '+1 649',
    currency: 'USD',
    nationality: 'Turks and Caicos Island',
  },
  TV: {
    name: 'Tuvalu',
    dial_code: '+688',
    currency: 'AUD',
    nationality: 'Tuvaluan',
  },
  UG: {
    name: 'Uganda',
    dial_code: '+256',
    currency: 'UGX',
    nationality: 'Ugandan',
  },
  UA: {
    name: 'Ukraine',
    dial_code: '+380',
    currency: 'UAH',
    nationality: 'Ukrainian',
  },
  AE: {
    name: 'United Arab Emirates',
    dial_code: '+971',
    currency: 'AED',
    nationality: 'Emirati, Emirian, Emiri',
  },
  GB: {
    name: 'United Kingdom',
    dial_code: '+44',
    currency: 'GBP',
    nationality: 'British, UK',
  },
  US: {
    name: 'United States',
    dial_code: '+1',
    currency: 'USD',
    nationality: 'American',
  },
  UY: {
    name: 'Uruguay',
    dial_code: '+598',
    currency: 'UYU',
    nationality: 'Uruguayan',
  },
  UZ: {
    name: 'Uzbekistan',
    dial_code: '+998',
    currency: 'UZS',
    nationality: 'Uzbekistani, Uzbek',
  },
  VU: {
    name: 'Vanuatu',
    dial_code: '+678',
    currency: 'VUV',
    nationality: 'Ni-Vanuatu, Vanuatuan',
  },
  VE: {
    name: 'Venezuela, Bolivarian Republic of',
    dial_code: '+58',
    currency: 'VEF',
    nationality: 'Venezuelan',
  },
  VN: {
    name: 'Viet Nam',
    dial_code: '+84',
    currency: 'VND',
    nationality: 'Vietnamese',
  },
  VI: {
    name: 'Virgin Islands',
    dial_code: '+1 340',
    currency: 'USD',
    nationality: 'U.S. Virgin Island',
  },
  YE: {
    name: 'Yemen',
    dial_code: '+967',
    currency: 'YER',
    nationality: 'Yemeni',
  },
  ZM: {
    name: 'Zambia',
    dial_code: '+260',
    currency: 'ZMK',
    nationality: 'Zambian',
  },
  ZW: {
    name: 'Zimbabwe',
    dial_code: '+263',
    currency: 'ZWD',
    nationality: 'Zimbabwean',
  },
};
